# Generated by Django 4.2.5 on 2023-10-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description_small',
            field=models.TextField(blank=True, null=True),
        ),
    ]
