# Generated by Django 4.2.5 on 2023-10-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listing_description_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default='no-image-available.jpg', null=True, upload_to='uploads'),
        ),
    ]
