# Generated by Django 4.2.5 on 2023-10-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_listing_category_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, default='not-tagged', max_length=100, null=True),
        ),
    ]
